import type { Card, Tower } from './types';

const CARD_CDN_URL = 'https://cdn.royaleapi.com/static/img/cards-256/';
const TOWER_CDN_URL = 'https://cdn.royaleapi.com/static/img/tower-troops/';

export const ARENAS = [
  { number: 1, name: 'Goblin Stadium' },
  { number: 2, name: 'Bone Pit' },
  { number: 3, name: 'Barbarian Bowl' },
  { number: 4, 'name': 'P.E.K.K.A\'s Playhouse' },
  { number: 5, name: 'Spell Valley' },
  { number: 6, 'name': 'Builder\'s Workshop' },
  { number: 7, name: 'Royal Arena' },
  { number: 8, name: 'Frozen Peak' },
  { number: 9, name: 'Jungle Arena' },
  { number: 10, name: 'Hog Mountain' },
  { number: 11, name: 'Electro Valley' },
  { number: 12, name: 'Spooky Town' },
  { number: 13, 'name': 'Rascal\'s Hideout' },
  { number: 14, name: 'Serenity Peak' },
  { number: 15, 'name': 'Miner\'s Mine' },
  { number: 16, 'name': 'Executioner\'s Kitchen' },
  { number: 17, name: 'Royal Crypt' },
  { number: 18, name: 'Silent Sanctuary' },
  { number: 19, name: 'Dragon Spa' },
  { number: 20, name: 'Boot Camp' },
  { number: 21, name: 'Clash Fest' },
  { number: 22, name: 'PANCAKES!' },
  { number: 23, name: 'Legendary Arena' },
];

export const TOWERS: Tower[] = [
    { name: 'Princess Tower', image: `${CARD_CDN_URL}princess-tower.png`},
    { name: 'Cannoneer', image: `${TOWER_CDN_URL}cannoneer.png`},
    { name: 'Dagger Duchess', image: `${TOWER_CDN_URL}dagger-duchess.png`},
    { name: 'Royal Chef', image: `${TOWER_CDN_URL}royal-chef.png`},
];

export const TOWER_MAP = new Map(TOWERS.map(tower => [tower.name.toLowerCase(), tower]));

// Comprehensive list of all cards based on user input
export const CARDS: Card[] = [
  // Champions (Arena 23)
  { name: 'Archer Queen', elixir: 5, image: `${CARD_CDN_URL}archer-queen.png`, arena: 23 },
  { name: 'Golden Knight', elixir: 4, image: `${CARD_CDN_URL}golden-knight.png`, arena: 23 },
  { name: 'Little Prince', elixir: 3, image: `${CARD_CDN_URL}little-prince.png`, arena: 23 },
  { name: 'Mighty Miner', elixir: 4, image: `${CARD_CDN_URL}mighty-miner.png`, arena: 23 },
  { name: 'Monk', elixir: 5, image: `${CARD_CDN_URL}monk.png`, arena: 22 },
  { name: 'Skeleton King', elixir: 4, image: `${CARD_CDN_URL}skeleton-king.png`, arena: 23 },

  // Legendary
  { name: 'Bandit', elixir: 3, image: `${CARD_CDN_URL}bandit.png`, arena: 9 },
  { name: 'Electro Wizard', elixir: 4, image: `${CARD_CDN_URL}electro-wizard.png`, arena: 11 },
  { name: 'Fisherman', elixir: 3, image: `${CARD_CDN_URL}fisherman.png`, arena: 14 },
  { name: 'Graveyard', elixir: 5, image: `${CARD_CDN_URL}graveyard.png`, arena: 12 },
  { name: 'Ice Wizard', elixir: 3, image: `${CARD_CDN_URL}ice-wizard.png`, arena: 8 },
  { name: 'Inferno Dragon', elixir: 4, image: `${CARD_CDN_URL}inferno-dragon.png`, arena: 16 },
  { name: 'Lava Hound', elixir: 7, image: `${CARD_CDN_URL}lava-hound.png`, arena: 19 },
  { name: 'Lumberjack', elixir: 4, image: `${CARD_CDN_URL}lumberjack.png`, arena: 16 },
  { name: 'Magic Archer', elixir: 4, image: `${CARD_CDN_URL}magic-archer.png`, arena: 17 },
  { name: 'Mega Knight', elixir: 7, image: `${CARD_CDN_URL}mega-knight.png`, arena: 21 },
  { name: 'Miner', elixir: 3, image: `${CARD_CDN_URL}miner.png`, arena: 15 },
  { name: 'Mother Witch', elixir: 4, image: `${CARD_CDN_URL}mother-witch.png`, arena: 18 },
  { name: 'Night Witch', elixir: 4, image: `${CARD_CDN_URL}night-witch.png`, arena: 18 },
  { name: 'Phoenix', elixir: 4, image: `${CARD_CDN_URL}phoenix.png`, arena: 22 },
  { name: 'Princess', elixir: 3, image: `${CARD_CDN_URL}princess.png`, arena: 7 },
  { name: 'Ram Rider', elixir: 5, image: `${CARD_CDN_URL}ram-rider.png`, arena: 10 },
  { name: 'Royal Ghost', elixir: 3, image: `${CARD_CDN_URL}royal-ghost.png`, arena: 17 },
  { name: 'Sparky', elixir: 6, image: `${CARD_CDN_URL}sparky.png`, arena: 20 },
  { name: 'The Log', elixir: 2, image: `${CARD_CDN_URL}the-log.png`, arena: 15 },

  // Epic
  { name: 'Baby Dragon', elixir: 4, image: `${CARD_CDN_URL}baby-dragon.png`, arena: 0 },
  { name: 'Balloon', elixir: 5, image: `${CARD_CDN_URL}balloon.png`, arena: 6 },
  { name: 'Barbarian Barrel', elixir: 2, image: `${CARD_CDN_URL}barbarian-barrel.png`, arena: 13 },
  { name: 'Barbarian Hut', elixir: 7, image: `${CARD_CDN_URL}barbarian-hut.png`, arena: 3 },
  { name: 'Battle Healer', elixir: 4, image: `${CARD_CDN_URL}battle-healer.png`, arena: 11 },
  { name: 'Bowler', elixir: 5, image: `${CARD_CDN_URL}bowler.png`, arena: 8 },
  { name: 'Cannon Cart', elixir: 5, image: `${CARD_CDN_URL}cannon-cart.png`, arena: 21 },
  { name: 'Clone', elixir: 3, image: `${CARD_CDN_URL}clone.png`, arena: 8 },
  { name: 'Dark Prince', elixir: 4, image: `${CARD_CDN_URL}dark-prince.png`, arena: 7 },
  { name: 'Electro Dragon', elixir: 5, image: `${CARD_CDN_URL}electro-dragon.png`, arena: 11 },
  { name: 'Electro Giant', elixir: 7, image: `${CARD_CDN_URL}electro-giant.png`, arena: 11 },
  { name: 'Elixir Golem', elixir: 3, image: `${CARD_CDN_URL}elixir-golem.png`, arena: 14 },
  { name: 'Executioner', elixir: 5, image: `${CARD_CDN_URL}executioner.png`, arena: 13 },
  { name: 'Freeze', elixir: 4, image: `${CARD_CDN_URL}freeze.png`, arena: 4 },
  { name: 'Giant Skeleton', elixir: 6, image: `${CARD_CDN_URL}giant-skeleton.png`, arena: 2 },
  { name: 'Goblin Barrel', elixir: 3, image: `${CARD_CDN_URL}goblin-barrel.png`, arena: 1 },
  { name: 'Goblin Drill', elixir: 4, image: `${CARD_CDN_URL}goblin-drill.png`, arena: 20 },
  { name: 'Goblin Giant', elixir: 6, image: `${CARD_CDN_URL}goblin-giant.png`, arena: 9 },
  { name: 'Golem', elixir: 8, image: `${CARD_CDN_URL}golem.png`, arena: 6 },
  { name: 'Guards', elixir: 3, image: `${CARD_CDN_URL}guards.png`, arena: 7 },
  { name: 'Hunter', elixir: 4, image: `${CARD_CDN_URL}hunter.png`, arena: 9 },
  { name: 'Lightning', elixir: 6, image: `${CARD_CDN_URL}lightning.png`, arena: 8 },
  { name: 'Mirror', elixir: 1, image: `${CARD_CDN_URL}mirror.png`, arena: 5 },
  { name: 'P.E.K.K.A.', elixir: 7, image: `${CARD_CDN_URL}pekka.png`, arena: 4 },
  { name: 'Poison', elixir: 4, image: `${CARD_CDN_URL}poison.png`, arena: 5 },
  { name: 'Prince', elixir: 5, image: `${CARD_CDN_URL}prince.png`, arena: 0 },
  { name: 'Rage', elixir: 2, image: `${CARD_CDN_URL}rage.png`, arena: 3 },
  { name: 'Royal Hogs', elixir: 5, image: `${CARD_CDN_URL}royal-hogs.png`, arena: 7 },
  { name: 'Royal Recruits', elixir: 7, image: `${CARD_CDN_URL}royal-recruits.png`, arena: 7 },
  { name: 'Skeleton Army', elixir: 3, image: `${CARD_CDN_URL}skeleton-army.png`, arena: 0 },
  { name: 'Skeleton Dragons', elixir: 4, image: `${CARD_CDN_URL}skeleton-dragons.png`, arena: 19 },
  { name: 'Tornado', elixir: 3, image: `${CARD_CDN_URL}tornado.png`, arena: 15 },
  { name: 'Vines', elixir: 1, image: `${CARD_CDN_URL}vines.png`, arena: 23 },
  { name: 'Void', elixir: 3, image: `${CARD_CDN_URL}void.png`, arena: 23 },
  { name: 'Wall Breakers', elixir: 2, image: `${CARD_CDN_URL}wall-breakers.png`, arena: 12 },
  { name: 'Witch', elixir: 5, image: `${CARD_CDN_URL}witch.png`, arena: 2 },
  { name: 'X-Bow', elixir: 6, image: `${CARD_CDN_URL}x-bow.png`, arena: 6 },
  
  // Rare
  { name: 'Battle Ram', elixir: 4, image: `${CARD_CDN_URL}battle-ram.png`, arena: 3 },
  { name: 'Bomb Tower', elixir: 4, image: `${CARD_CDN_URL}bomb-tower.png`, arena: 2 },
  { name: 'Dart Goblin', elixir: 3, image: `${CARD_CDN_URL}dart-goblin.png`, arena: 9 },
  { name: 'Earthquake', elixir: 3, image: `${CARD_CDN_URL}earthquake.png`, arena: 14 },
  { name: 'Elixir Collector', elixir: 6, image: `${CARD_CDN_URL}elixir-collector.png`, arena: 10 },
  { name: 'Fireball', elixir: 4, image: `${CARD_CDN_URL}fireball.png`, arena: 0 },
  { name: 'Flying Machine', elixir: 4, image: `${CARD_CDN_URL}flying-machine.png`, arena: 6 },
  { name: 'Furnace', elixir: 4, image: `${CARD_CDN_URL}furnace.png`, arena: 5 },
  { name: 'Giant', elixir: 5, image: `${CARD_CDN_URL}giant.png`, arena: 0 },
  { name: 'Goblin Cage', elixir: 4, image: `${CARD_CDN_URL}goblin-cage.png`, arena: 10 },
  { name: 'Goblin Hut', elixir: 5, image: `${CARD_CDN_URL}goblin-hut.png`, arena: 1 },
  { name: 'Hog Rider', elixir: 4, image: `${CARD_CDN_URL}hog-rider.png`, arena: 4 },
  { name: 'Ice Golem', elixir: 2, image: `${CARD_CDN_URL}ice-golem.png`, arena: 8 },
  { name: 'Inferno Tower', elixir: 5, image: `${CARD_CDN_URL}inferno-tower.png`, arena: 4 },
  { name: 'Mega Minion', elixir: 3, image: `${CARD_CDN_URL}mega-minion.png`, arena: 3 },
  { name: 'Mini P.E.K.K.A.', elixir: 4, image: `${CARD_CDN_URL}mini-pekka.png`, arena: 0 },
  { name: 'Musketeer', elixir: 4, image: `${CARD_CDN_URL}musketeer.png`, arena: 0 },
  { name: 'Rocket', elixir: 6, image: `${CARD_CDN_URL}rocket.png`, arena: 6 },
  { name: 'Royal Delivery', elixir: 3, image: `${CARD_CDN_URL}royal-delivery.png`, arena: 7 },
  { name: 'Three Musketeers', elixir: 9, image: `${CARD_CDN_URL}three-musketeers.png`, arena: 7 },
  { name: 'Tombstone', elixir: 3, image: `${CARD_CDN_URL}tombstone.png`, arena: 2 },
  { name: 'Valkyrie', elixir: 4, image: `${CARD_CDN_URL}valkyrie.png`, arena: 1 },
  { name: 'Wizard', elixir: 5, image: `${CARD_CDN_URL}wizard.png`, arena: 5 },
  { name: 'Zappies', elixir: 4, image: `${CARD_CDN_URL}zappies.png`, arena: 11 },

  // Common
  { name: 'Archers', elixir: 3, image: `${CARD_CDN_URL}archers.png`, arena: 0 },
  { name: 'Arrows', elixir: 3, image: `${CARD_CDN_URL}arrows.png`, arena: 0 },
  { name: 'Barbarians', elixir: 5, image: `${CARD_CDN_URL}barbarians.png`, arena: 3 },
  { name: 'Bats', elixir: 2, image: `${CARD_CDN_URL}bats.png`, arena: 12 },
  { name: 'Bomber', elixir: 2, image: `${CARD_CDN_URL}bomber.png`, arena: 0 },
  { name: 'Cannon', elixir: 3, image: `${CARD_CDN_URL}cannon.png`, arena: 3 },
  { name: 'Elite Barbarians', elixir: 6, image: `${CARD_CDN_URL}elite-barbarians.png`, arena: 10 },
  { name: 'Fire Spirit', elixir: 1, image: `${CARD_CDN_URL}fire-spirit.png`, arena: 5 },
  { name: 'Firecracker', elixir: 3, image: `${CARD_CDN_URL}firecracker.png`, arena: 10 },
  { name: 'Goblins', elixir: 2, image: `${CARD_CDN_URL}goblins.png`, arena: 0 },
  { name: 'Goblin Gang', elixir: 3, image: `${CARD_CDN_URL}goblin-gang.png`, arena: 9 },
  { name: 'Heal Spirit', elixir: 1, image: `${CARD_CDN_URL}heal-spirit.png`, arena: 10 },
  { name: 'Ice Spirit', elixir: 1, image: `${CARD_CDN_URL}ice-spirit.png`, arena: 8 },
  { name: 'Knight', elixir: 3, image: `${CARD_CDN_URL}knight.png`, arena: 0 },
  { name: 'Minions', elixir: 3, image: `${CARD_CDN_URL}minions.png`, arena: 2 },
  { name: 'Minion Horde', elixir: 5, image: `${CARD_CDN_URL}minion-horde.png`, arena: 4 },
  { name: 'Mortar', elixir: 4, image: `${CARD_CDN_URL}mortar.png`, arena: 6 },
  { name: 'Rascals', elixir: 5, image: `${CARD_CDN_URL}rascals.png`, arena: 13 },
  { name: 'Royal Giant', elixir: 6, image: `${CARD_CDN_URL}royal-giant.png`, arena: 7 },
  { name: 'Skeletons', elixir: 1, image: `${CARD_CDN_URL}skeletons.png`, arena: 2 },
  { name: 'Skeleton Barrel', elixir: 3, image: `${CARD_CDN_URL}skeleton-barrel.png`, arena: 6 },
  { name: 'Snowball', elixir: 2, image: `${CARD_CDN_URL}giant-snowball.png`, arena: 12 },
  { name: 'Spear Goblins', elixir: 2, image: `${CARD_CDN_URL}spear-goblins.png`, arena: 1 },
  { name: 'Tesla', elixir: 4, image: `${CARD_CDN_URL}tesla.png`, arena: 4 },
  { name: 'Zap', elixir: 2, image: `${CARD_CDN_URL}zap.png`, arena: 5 },
  { name: 'Electro Spirit', elixir: 1, image: `${CARD_CDN_URL}electro-spirit.png`, arena: 11 },

  // Evolutions (Unlocked with King Level, not arena - setting to 7 as a baseline)
  { name: 'Evolution P.E.K.K.A.', elixir: 7, image: `${CARD_CDN_URL}pekka-ev1.png`, arena: 7 },
  { name: 'Evolution Knight', elixir: 3, image: `${CARD_CDN_URL}knight-ev1.png`, arena: 7 },
  { name: 'Evolution Skeletons', elixir: 1, image: `${CARD_CDN_URL}skeletons-ev1.png`, arena: 7 },
  { name: 'Evolution Royal Giant', elixir: 6, image: `${CARD_CDN_URL}royal-giant-ev1.png`, arena: 7 },
  { name: 'Evolution Bats', elixir: 2, image: `${CARD_CDN_URL}bats-ev1.png`, arena: 7 },
  { name: 'Evolution Mortar', elixir: 4, image: `${CARD_CDN_URL}mortar-ev1.png`, arena: 7 },
  { name: 'Evolution Baby Dragon', elixir: 4, image: `${CARD_CDN_URL}baby-dragon-ev1.png`, arena: 7 },
  { name: 'Evolution Goblin Barrel', elixir: 3, image: `${CARD_CDN_URL}goblin-barrel-ev1.png`, arena: 7 },
  { name: 'Evolution Musketeer', elixir: 4, image: `${CARD_CDN_URL}musketeer-ev1.png`, arena: 7 },
  { name: 'Evolution Goblin Cage', elixir: 4, image: `${CARD_CDN_URL}goblin-cage-ev1.png`, arena: 7 },
  { name: 'Evolution Ice Spirit', elixir: 1, image: `${CARD_CDN_URL}ice-spirit-ev1.png`, arena: 7 },
  { name: 'Evolution Skeleton Barrel', elixir: 3, image: `${CARD_CDN_URL}skeleton-barrel-ev1.png`, arena: 7 },
  { name: 'Evolution Cannon', elixir: 3, image: `${CARD_CDN_URL}cannon-ev1.png`, arena: 7 },
  { name: 'Evolution Snowball', elixir: 2, image: `${CARD_CDN_URL}giant-snowball-ev1.png`, arena: 7 },
  { name: 'Evolution Lumberjack', elixir: 4, image: `${CARD_CDN_URL}lumberjack-ev1.png`, arena: 7 },
  { name: 'Evolution Inferno Dragon', elixir: 4, image: `${CARD_CDN_URL}inferno-dragon-ev1.png`, arena: 7 },
  { name: 'Evolution Witch', elixir: 5, image: `${CARD_CDN_URL}witch-ev1.png`, arena: 7 },
  { name: 'Evolution Hunter', elixir: 4, image: `${CARD_CDN_URL}hunter-ev1.png`, arena: 7 },
  { name: 'Evolution Executioner', elixir: 5, image: `${CARD_CDN_URL}executioner-ev1.png`, arena: 7 },
  { name: 'Evolution Wall Breakers', elixir: 2, image: `${CARD_CDN_URL}wall-breakers-ev1.png`, arena: 7 },
  { name: 'Evolution Goblin Giant', elixir: 6, image: `${CARD_CDN_URL}goblin-giant-ev1.png`, arena: 7 },
  { name: 'Evolution Battle Ram', elixir: 4, image: `${CARD_CDN_URL}battle-ram-ev1.png`, arena: 7 },
  { name: 'Evolution Royal Recruits', elixir: 7, image: `${CARD_CDN_URL}royal-recruits-ev1.png`, arena: 7 },
  { name: 'Evolution Firecracker', elixir: 3, image: `${CARD_CDN_URL}firecracker-ev1.png`, arena: 7 },
  { name: 'Evolution Tesla', elixir: 4, image: `${CARD_CDN_URL}tesla-ev1.png`, arena: 7 },
  { name: 'Evolution Goblin Drill', elixir: 4, image: `${CARD_CDN_URL}goblin-drill-ev1.png`, arena: 7 },
  { name: 'Evolution Mega Knight', elixir: 7, image: `${CARD_CDN_URL}mega-knight-ev1.png`, arena: 7 },
  { name: 'Evolution Furnace', elixir: 4, image: `${CARD_CDN_URL}furnace-ev1.png`, arena: 7 },
  { name: 'Evolution Wizard', elixir: 5, image: `${CARD_CDN_URL}wizard-ev1.png`, arena: 7 },
  { name: 'Evolution Dart Goblin', elixir: 3, image: `${CARD_CDN_URL}dart-goblin-ev1.png`, arena: 7 },
  { name: 'Evolution Barbarians', elixir: 5, image: `${CARD_CDN_URL}barbarians-ev1.png`, arena: 7 },
  { name: 'Evolution Bomber', elixir: 2, image: `${CARD_CDN_URL}bomber-ev1.png`, arena: 7 },
  { name: 'Evolution Electro Dragon', elixir: 5, image: `${CARD_CDN_URL}electro-dragon-ev1.png`, arena: 7 },
  { name: 'Evolution Archers', elixir: 3, image: `${CARD_CDN_URL}archers-ev1.png`, arena: 7 },
  { name: 'Evolution Valkyrie', elixir: 4, image: `${CARD_CDN_URL}valkyrie-ev1.png`, arena: 7 },
];

export const CARD_MAP = new Map(CARDS.map(card => [card.name.toLowerCase(), card]));
